# Generated by Django 4.2.3 on 2023-08-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_register_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
