# Generated by Django 4.2.3 on 2023-08-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
