# Generated by Django 4.2.3 on 2023-08-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(upload_to='img/')),
                ('company_name', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('languages', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=100)),
            ],
        ),
    ]
