# Generated by Django 4.2.3 on 2023-08-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
