# Generated by Django 4.2.3 on 2023-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
