# Generated by Django 4.2.3 on 2023-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_showcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
