# Generated by Django 4.2.3 on 2023-08-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_adminregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
