# Generated by Django 4.2.3 on 2023-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
