# Generated by Django 4.2.3 on 2023-08-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_candidate_candidate_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidate',
        ),
    ]
