# Generated by Django 4.2.3 on 2023-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_delete_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_image', models.ImageField(upload_to='img/')),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_laguages', models.CharField(max_length=100)),
                ('candidate_developer', models.CharField(max_length=50)),
                ('candidate_city', models.CharField(max_length=50)),
                ('candidate_number', models.IntegerField()),
            ],
        ),
    ]
