# Generated by Django 4.2.3 on 2023-08-11 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
