# Generated by Django 4.2.3 on 2023-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apply_job',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
