# Generated by Django 4.2.3 on 2023-08-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showcompany',
        ),
    ]
