# Generated by Django 4.2.3 on 2023-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_delete_showcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='working_hours',
            field=models.TimeField(null=True),
        ),
    ]
