# Generated by Django 4.2.3 on 2023-08-11 18:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_job_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='working_hours',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
