# Generated by Django 4.2.3 on 2023-08-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alter_job_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='developer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
