# Generated by Django 4.2.3 on 2023-08-12 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apply_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
