# Generated by Django 4.2.3 on 2023-08-12 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_profile_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apply_time',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 11, 51, 45, 573403)),
        ),
    ]
