# Generated by Django 4.2.3 on 2023-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
