# Generated by Django 4.2.3 on 2023-08-12 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_applyjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='apply_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
