# Generated by Django 4.2.3 on 2023-08-14 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0040_applyjobs_apply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_image',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
