# Generated by Django 4.2.3 on 2023-08-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_remove_candidate_candidate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
