# Generated by Django 4.2.3 on 2023-08-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_profile_language_profile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='contact',
        ),
    ]
