# Generated by Django 4.2.3 on 2023-08-14 05:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
