# Generated by Django 4.2.3 on 2023-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
