# Generated by Django 4.2.3 on 2023-08-14 06:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
