# Generated by Django 4.2.3 on 2023-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_profile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
